import { NutritionFood, NutritionCategory } from './types';

export const nutritionCategories: NutritionCategory[] = [
  { id: 'all', name: 'All', icon: '🍽️', description: 'All nutritious foods' },
  { id: 'drinks', name: 'Healthy Drinks', icon: '🥤', description: 'Zero sugar healthy beverages' },
  { id: 'shakes', name: 'Protein Shakes', icon: '🥛', description: 'No preservatives shakes' },
  { id: 'mealbox', name: 'Meal Boxes', icon: '📦', description: 'Complete nutrition meals' },
  { id: 'bowls', name: 'Power Bowls', icon: '🥗', description: 'Nutrient-dense bowls' },
];

export const nutrientFilters = [
  { id: 'vitamin-d', name: 'Vitamin D', icon: '☀️' },
  { id: 'omega-3', name: 'Omega-3', icon: '🐟' },
  { id: 'collagen', name: 'Collagen', icon: '✨' },
  { id: 'iron', name: 'Iron', icon: '💪' },
  { id: 'calcium', name: 'Calcium', icon: '🦴' },
  { id: 'protein', name: 'Protein', icon: '🥩' },
  { id: 'fiber', name: 'Fiber', icon: '🌾' },
  { id: 'antioxidants', name: 'Antioxidants', icon: '🫐' },
  { id: 'vitamin-b12', name: 'Vitamin B12', icon: '🔴' },
  { id: 'vitamin-c', name: 'Vitamin C', icon: '🍊' },
  { id: 'zinc', name: 'Zinc', icon: '⚡' },
];

export const techVendors = [
  { id: 'freshly', name: 'Freshly Farms', logo: '🌱', tagline: 'Farm to Table in 30 mins' },
  { id: 'nutribox', name: 'NutriBox', logo: '📦', tagline: 'Your Daily Nutrition Partner' },
  { id: 'greenbite', name: 'GreenBite', logo: '🥗', tagline: 'Healthy Eating Made Easy' },
  { id: 'vitadelivery', name: 'VitaDelivery', logo: '🚀', tagline: 'Superfoods at Your Door' },
  { id: 'purehealth', name: 'PureHealth Kitchen', logo: '💚', tagline: 'Zero Preservatives Guaranteed' },
];

export const nutritionFoods: NutritionFood[] = [
  // Healthy Drinks - Zero Added Sugar
  {
    id: '1',
    name: 'Green Detox Elixir',
    description: 'Fresh spinach, cucumber, celery, ginger & lemon - Zero sugar, 100% natural',
    benefits: '✅ Detoxifies liver & kidneys ✅ Boosts immunity ✅ Improves skin clarity ✅ Reduces inflammation ✅ Aids weight loss',
    price: 129,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['iron', 'vitamin-c', 'antioxidants'],
    calories: 45,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '2',
    name: 'Beetroot Vitality Juice',
    description: 'Fresh beetroot, carrot, apple & ginger - Natural sweetness, no added sugar',
    benefits: '✅ Lowers blood pressure ✅ Improves blood flow ✅ Enhances stamina ✅ Rich in nitrates for heart health ✅ Supports liver function',
    price: 119,
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['iron', 'fiber', 'vitamin-c'],
    calories: 68,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '3',
    name: 'Tender Coconut Water',
    description: 'Fresh tender coconut water - Natural electrolytes, zero preservatives',
    benefits: '✅ Natural hydration ✅ Rich in potassium ✅ Prevents kidney stones ✅ Regulates blood sugar ✅ Supports heart health',
    price: 79,
    image: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?w=400',
    category: 'drinks',
    season: ['summer'],
    nutrients: ['calcium', 'zinc', 'antioxidants'],
    calories: 46,
    rating: 4.9,
    deliveryTime: '10-15 min',
    vendor: 'NutriBox',
  },
  {
    id: '4',
    name: 'Ayurvedic Immunity Kadha',
    description: 'Turmeric, tulsi, black pepper, ginger & raw honey - Traditional immunity booster',
    benefits: '✅ Fights infections ✅ Reduces cold & cough ✅ Anti-inflammatory ✅ Boosts respiratory health ✅ Strengthens immune system',
    price: 99,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
    category: 'drinks',
    season: ['winter', 'monsoon'],
    nutrients: ['antioxidants', 'vitamin-c', 'zinc'],
    calories: 35,
    rating: 4.7,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '5',
    name: 'ABC Skin Glow Juice',
    description: 'Apple, Beetroot, Carrot juice - Zero sugar detox drink for radiant skin',
    benefits: '✅ Glowing skin ✅ Prevents acne ✅ Rich in beta-carotene ✅ Improves eyesight ✅ Natural blood purifier',
    price: 139,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['vitamin-c', 'iron', 'fiber'],
    calories: 72,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'GreenBite',
  },
  {
    id: '6',
    name: 'Amla Aloe Vera Shot',
    description: 'Fresh amla & aloe vera - Vitamin C powerhouse, no preservatives',
    benefits: '✅ 20x more Vitamin C than orange ✅ Promotes hair growth ✅ Improves digestion ✅ Anti-aging properties ✅ Boosts collagen',
    price: 89,
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['vitamin-c', 'collagen', 'antioxidants'],
    calories: 28,
    rating: 4.6,
    deliveryTime: '10-15 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '7',
    name: 'Wheatgrass Wellness Shot',
    description: 'Fresh wheatgrass juice - Chlorophyll-rich superfood, organic',
    benefits: '✅ Powerful detoxifier ✅ Increases hemoglobin ✅ Alkalizes body ✅ Boosts energy ✅ Supports weight loss',
    price: 99,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['iron', 'antioxidants', 'vitamin-c'],
    calories: 25,
    rating: 4.7,
    deliveryTime: '10-15 min',
    vendor: 'GreenBite',
  },

  // Protein Shakes - No Preservatives
  {
    id: '8',
    name: 'Peanut Butter Banana Shake',
    description: 'Natural peanut butter, banana, oats & almond milk - 25g protein, zero sugar',
    benefits: '✅ 25g plant protein ✅ Sustained energy ✅ Muscle recovery ✅ Heart-healthy fats ✅ Rich in potassium',
    price: 179,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'omega-3'],
    calories: 320,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '9',
    name: 'Traditional Sattu Shake',
    description: 'Roasted gram flour, jaggery, cardamom & milk - Ancient protein drink',
    benefits: '✅ 20g complete protein ✅ Cooling effect ✅ Diabetic-friendly ✅ Improves digestion ✅ Rich in fiber',
    price: 129,
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400',
    category: 'shakes',
    season: ['summer'],
    nutrients: ['protein', 'iron', 'fiber'],
    calories: 280,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '10',
    name: 'Ragi Almond Power Shake',
    description: 'Finger millet, almonds, dates & coconut milk - Calcium & protein rich',
    benefits: '✅ 3x more calcium than milk ✅ Gluten-free ✅ Controls blood sugar ✅ Strengthens bones ✅ Natural weight manager',
    price: 159,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['calcium', 'protein', 'iron'],
    calories: 260,
    rating: 4.7,
    deliveryTime: '15-20 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '11',
    name: 'Spinach Avocado Green Shake',
    description: 'Fresh spinach, avocado, banana & hemp seeds - Green protein powerhouse',
    benefits: '✅ Complete amino acids ✅ Brain-boosting omega-3 ✅ Iron for energy ✅ Fiber for gut health ✅ Healthy fats',
    price: 199,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'iron'],
    calories: 290,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'GreenBite',
  },
  {
    id: '12',
    name: 'Mixed Dry Fruits Shake',
    description: 'Almonds, cashews, walnuts, dates & A2 milk - Natural protein bomb',
    benefits: '✅ 30g protein ✅ Omega-3 for brain ✅ Vitamin E for skin ✅ Energy booster ✅ Muscle building',
    price: 219,
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'vitamin-b12'],
    calories: 350,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '13',
    name: 'Sprouted Moong Shake',
    description: 'Sprouted moong, banana, jaggery & cardamom - Plant protein shake',
    benefits: '✅ Easily digestible protein ✅ Rich in enzymes ✅ Boosts metabolism ✅ Low glycemic ✅ Gut-friendly',
    price: 149,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 240,
    rating: 4.6,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },

  // Meal Boxes - Complete Nutrition (All Healthy)
  {
    id: '14',
    name: 'Dal Roti Thali Box',
    description: 'Yellow dal tadka, 3 multigrain rotis, jeera rice, salad & pickle',
    benefits: '✅ Complete protein (dal+roti combo) ✅ High fiber ✅ Balanced carbs ✅ Probiotic pickle ✅ Low fat cooking',
    price: 189,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 480,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '15',
    name: 'Baby Corn Stir-Fry Box',
    description: 'Baby corn, bell peppers, broccoli in garlic sauce with brown rice',
    benefits: '✅ Low calorie ✅ High fiber ✅ Rich in Vitamin C ✅ Antioxidants ✅ Good for weight loss',
    price: 219,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['fiber', 'vitamin-c', 'protein'],
    calories: 380,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'GreenBite',
  },
  {
    id: '16',
    name: 'Grilled Paneer Tikka Box',
    description: 'Grilled paneer tikka (not fried), mint chutney, whole wheat paratha & raita',
    benefits: '✅ 25g protein ✅ Calcium for bones ✅ Probiotics in raita ✅ No deep frying ✅ Vitamin B12',
    price: 249,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'calcium', 'vitamin-b12'],
    calories: 450,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '17',
    name: 'Rajma Chawal Bowl',
    description: 'Punjabi rajma (kidney beans), jeera rice, onion salad & pickle',
    benefits: '✅ Plant-based protein ✅ Iron for hemoglobin ✅ Fiber for digestion ✅ Low fat ✅ Heart healthy',
    price: 179,
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 420,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'NutriBox',
  },
  {
    id: '18',
    name: 'Grilled Chicken Quinoa Box',
    description: 'Herb grilled chicken breast, quinoa, steamed veggies & hummus',
    benefits: '✅ 35g lean protein ✅ Complete amino acids ✅ Low carb ✅ Omega-3 ✅ Muscle building',
    price: 299,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'vitamin-b12'],
    calories: 420,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '19',
    name: 'Palak Paneer Meal Box',
    description: 'Creamy palak paneer, 2 whole wheat rotis, brown rice & cucumber raita',
    benefits: '✅ Iron-rich spinach ✅ Calcium from paneer ✅ Vitamin K ✅ Low calorie greens ✅ Eye health',
    price: 229,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['iron', 'calcium', 'protein'],
    calories: 460,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'GreenBite',
  },
  {
    id: '20',
    name: 'Bengali Fish Curry Box',
    description: 'Light fish curry, steamed rice, dal & mixed vegetable bhaji',
    benefits: '✅ Omega-3 fatty acids ✅ Brain health ✅ Heart protective ✅ Lean protein ✅ Anti-inflammatory',
    price: 279,
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['omega-3', 'protein', 'vitamin-b12'],
    calories: 450,
    rating: 4.9,
    deliveryTime: '30-35 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '21',
    name: 'Millet Khichdi Box',
    description: 'Foxtail millet, moong dal, ghee, vegetables & buttermilk',
    benefits: '✅ Gluten-free ✅ Diabetic friendly ✅ Easy to digest ✅ Gut healing ✅ Rich in minerals',
    price: 169,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['fiber', 'protein', 'iron'],
    calories: 320,
    rating: 4.7,
    deliveryTime: '25-30 min',
    vendor: 'PureHealth Kitchen',
  },

  // Power Bowls - Nutrient Dense
  {
    id: '22',
    name: 'Mixed Sprouts Protein Bowl',
    description: 'Moong, chana, moth sprouts with lemon, tomato, cucumber & green chutney',
    benefits: '✅ Living enzymes ✅ Easy absorption ✅ 15g protein ✅ Vitamin C ✅ Low calorie high nutrition',
    price: 149,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'vitamin-c'],
    calories: 180,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '23',
    name: 'Buddha Bowl Supreme',
    description: 'Quinoa, chickpeas, avocado, roasted veggies, greens & tahini dressing',
    benefits: '✅ Complete protein ✅ Healthy fats ✅ 10g fiber ✅ Anti-inflammatory ✅ Balanced macros',
    price: 269,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'omega-3'],
    calories: 380,
    rating: 4.9,
    deliveryTime: '20-25 min',
    vendor: 'GreenBite',
  },
  {
    id: '24',
    name: 'Egg White Veggie Bowl',
    description: 'Scrambled egg whites, sautéed spinach, mushrooms & whole wheat toast',
    benefits: '✅ Pure protein ✅ Zero cholesterol ✅ Low calorie ✅ Muscle friendly ✅ B vitamins',
    price: 199,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'vitamin-b12', 'iron'],
    calories: 250,
    rating: 4.7,
    deliveryTime: '20-25 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '25',
    name: 'Mediterranean Falafel Bowl',
    description: 'Baked falafel, hummus, tabbouleh, olives, cucumber & whole wheat pita',
    benefits: '✅ Plant protein ✅ Heart-healthy olive oil ✅ Fiber-rich ✅ Mediterranean diet benefits ✅ Anti-aging',
    price: 239,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 390,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '26',
    name: 'Oats Upma Bowl',
    description: 'Steel cut oats upma with vegetables, peanuts, curry leaves & coconut chutney',
    benefits: '✅ Beta-glucan for heart ✅ Slow release carbs ✅ Diabetic friendly ✅ Fiber-rich ✅ Weight management',
    price: 139,
    image: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['fiber', 'protein', 'vitamin-b12'],
    calories: 260,
    rating: 4.6,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '27',
    name: 'Poha Power Bowl',
    description: 'Flattened rice with peanuts, curry leaves, turmeric, lemon & fresh coriander',
    benefits: '✅ Iron fortified ✅ Low calorie ✅ Easy digestion ✅ Probiotic-friendly ✅ Energy boosting',
    price: 119,
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['iron', 'fiber', 'vitamin-c'],
    calories: 220,
    rating: 4.7,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '28',
    name: 'Chicken Tikka Protein Bowl',
    description: 'Grilled chicken tikka, mint rice, grilled veggies, greens & yogurt dip',
    benefits: '✅ 40g lean protein ✅ Low fat cooking ✅ Complete meal ✅ Muscle recovery ✅ High satiety',
    price: 279,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'vitamin-b12', 'zinc'],
    calories: 380,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '29',
    name: 'Idli Sambar Bowl',
    description: 'Steamed rice & urad dal idlis with vegetable sambar & coconut chutney',
    benefits: '✅ Fermented probiotics ✅ Easy digestion ✅ Complete protein ✅ Low fat ✅ Gut-friendly',
    price: 129,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 280,
    rating: 4.8,
    deliveryTime: '20-25 min',
    vendor: 'NutriBox',
  },
  {
    id: '30',
    name: 'Tofu Teriyaki Bowl',
    description: 'Grilled tofu, brown rice, edamame, broccoli, carrots & teriyaki glaze',
    benefits: '✅ Plant protein ✅ Isoflavones for hormones ✅ Bone health ✅ Heart protective ✅ Low cholesterol',
    price: 249,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'calcium', 'iron'],
    calories: 340,
    rating: 4.7,
    deliveryTime: '25-30 min',
    vendor: 'GreenBite',
  },
];
