import { NutritionFood, NutritionCategory } from './types';

export const nutritionCategories: NutritionCategory[] = [
  { id: 'all', name: 'All', icon: '🍽️', description: 'All nutritious foods' },
  { id: 'fruits', name: 'Fruits', icon: '🍎', description: 'Fresh seasonal fruits' },
  { id: 'vegetables', name: 'Vegetables', icon: '🥬', description: 'Organic vegetables' },
  { id: 'salads', name: 'Salads', icon: '🥗', description: 'Ready-to-eat salads' },
  { id: 'smoothies', name: 'Smoothies', icon: '🥤', description: 'Nutrient-packed drinks' },
];

export const nutrientFilters = [
  { id: 'vitamin-d', name: 'Vitamin D', icon: '☀️' },
  { id: 'omega-3', name: 'Omega-3', icon: '🐟' },
  { id: 'collagen', name: 'Collagen', icon: '✨' },
  { id: 'iron', name: 'Iron', icon: '💪' },
  { id: 'calcium', name: 'Calcium', icon: '🦴' },
  { id: 'protein', name: 'Protein', icon: '🥩' },
  { id: 'fiber', name: 'Fiber', icon: '🌾' },
  { id: 'antioxidants', name: 'Antioxidants', icon: '🫐' },
];

export const techVendors = [
  { id: 'freshly', name: 'Freshly Farms', logo: '🌱', tagline: 'Farm to Table in 30 mins' },
  { id: 'nutribox', name: 'NutriBox', logo: '📦', tagline: 'Your Daily Nutrition Partner' },
  { id: 'greenbite', name: 'GreenBite', logo: '🥗', tagline: 'Healthy Eating Made Easy' },
  { id: 'vitadelivery', name: 'VitaDelivery', logo: '🚀', tagline: 'Superfoods at Your Door' },
];

export const nutritionFoods: NutritionFood[] = [
  // Fruits
  {
    id: '1',
    name: 'Seasonal Orange Box',
    description: 'Fresh Nagpur oranges rich in Vitamin C & antioxidants',
    price: 149,
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400',
    category: 'fruits',
    season: ['winter'],
    nutrients: ['vitamin-d', 'antioxidants', 'fiber'],
    calories: 47,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '2',
    name: 'Berry Blast Pack',
    description: 'Mixed berries - Strawberries, Blueberries & Raspberries',
    price: 299,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400',
    category: 'fruits',
    season: ['summer', 'monsoon'],
    nutrients: ['antioxidants', 'vitamin-d', 'fiber'],
    calories: 32,
    rating: 4.9,
    deliveryTime: '20-25 min',
    vendor: 'NutriBox',
  },
  {
    id: '3',
    name: 'Avocado Premium',
    description: 'Creamy Hass avocados - perfect for omega-3 & healthy fats',
    price: 199,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400',
    category: 'fruits',
    season: ['all'],
    nutrients: ['omega-3', 'fiber', 'protein'],
    calories: 160,
    rating: 4.7,
    deliveryTime: '30-35 min',
    vendor: 'GreenBite',
  },
  {
    id: '4',
    name: 'Pomegranate Fresh',
    description: 'Ruby red pomegranates packed with iron & antioxidants',
    price: 129,
    image: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=400',
    category: 'fruits',
    season: ['winter'],
    nutrients: ['iron', 'antioxidants', 'fiber'],
    calories: 83,
    rating: 4.6,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
  // Vegetables
  {
    id: '5',
    name: 'Spinach & Kale Bundle',
    description: 'Organic leafy greens rich in iron, calcium & vitamins',
    price: 89,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
    category: 'vegetables',
    season: ['winter', 'monsoon'],
    nutrients: ['iron', 'calcium', 'vitamin-d'],
    calories: 23,
    rating: 4.8,
    deliveryTime: '20-25 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '6',
    name: 'Broccoli Fresh Cut',
    description: 'Farm-fresh broccoli florets - superfood for immunity',
    price: 79,
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400',
    category: 'vegetables',
    season: ['winter'],
    nutrients: ['fiber', 'protein', 'calcium'],
    calories: 55,
    rating: 4.5,
    deliveryTime: '25-30 min',
    vendor: 'NutriBox',
  },
  {
    id: '7',
    name: 'Sweet Potato Pack',
    description: 'Orange sweet potatoes - complex carbs & beta-carotene',
    price: 69,
    image: 'https://images.unsplash.com/photo-1596097635121-14b63b7bbdf3?w=400',
    category: 'vegetables',
    season: ['all'],
    nutrients: ['fiber', 'vitamin-d', 'antioxidants'],
    calories: 86,
    rating: 4.7,
    deliveryTime: '20-25 min',
    vendor: 'GreenBite',
  },
  {
    id: '8',
    name: 'Mushroom Variety Box',
    description: 'Button, Shiitake & Oyster mushrooms - natural Vitamin D',
    price: 159,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    category: 'vegetables',
    season: ['all'],
    nutrients: ['vitamin-d', 'protein', 'iron'],
    calories: 22,
    rating: 4.6,
    deliveryTime: '30-35 min',
    vendor: 'VitaDelivery',
  },
  // Salads
  {
    id: '9',
    name: 'Greek Power Salad',
    description: 'Cucumber, tomato, olives, feta with olive oil dressing',
    price: 199,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    category: 'salads',
    season: ['all'],
    nutrients: ['omega-3', 'calcium', 'antioxidants'],
    calories: 180,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'GreenBite',
  },
  {
    id: '10',
    name: 'Quinoa Protein Bowl',
    description: 'Quinoa, chickpeas, avocado, greens with tahini',
    price: 249,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    category: 'salads',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 320,
    rating: 4.8,
    deliveryTime: '20-25 min',
    vendor: 'NutriBox',
  },
  {
    id: '11',
    name: 'Salmon Omega Salad',
    description: 'Grilled salmon, mixed greens, walnuts & citrus dressing',
    price: 349,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'salads',
    season: ['all'],
    nutrients: ['omega-3', 'protein', 'collagen'],
    calories: 380,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '12',
    name: 'Collagen Boost Bowl',
    description: 'Bone broth base, veggies, chicken & goji berries',
    price: 299,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    category: 'salads',
    season: ['all'],
    nutrients: ['collagen', 'protein', 'calcium'],
    calories: 290,
    rating: 4.7,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  // Smoothies
  {
    id: '13',
    name: 'Green Detox Smoothie',
    description: 'Spinach, apple, ginger, lemon & chia seeds',
    price: 149,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
    category: 'smoothies',
    season: ['all'],
    nutrients: ['iron', 'fiber', 'antioxidants'],
    calories: 120,
    rating: 4.6,
    deliveryTime: '10-15 min',
    vendor: 'NutriBox',
  },
  {
    id: '14',
    name: 'Berry Collagen Shake',
    description: 'Mixed berries, collagen peptides, almond milk & honey',
    price: 199,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    category: 'smoothies',
    season: ['all'],
    nutrients: ['collagen', 'antioxidants', 'protein'],
    calories: 180,
    rating: 4.8,
    deliveryTime: '10-15 min',
    vendor: 'GreenBite',
  },
  {
    id: '15',
    name: 'Omega Power Blend',
    description: 'Avocado, banana, flaxseed, walnut & coconut milk',
    price: 179,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400',
    category: 'smoothies',
    season: ['all'],
    nutrients: ['omega-3', 'fiber', 'protein'],
    calories: 250,
    rating: 4.7,
    deliveryTime: '10-15 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '16',
    name: 'Sunshine Vitamin D',
    description: 'Orange, mango, fortified almond milk & turmeric',
    price: 159,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    category: 'smoothies',
    season: ['summer'],
    nutrients: ['vitamin-d', 'antioxidants', 'calcium'],
    calories: 140,
    rating: 4.5,
    deliveryTime: '10-15 min',
    vendor: 'Freshly Farms',
  },
];
