import { NutritionFood, NutritionCategory } from './types';

export const nutritionCategories: NutritionCategory[] = [
  { id: 'all', name: 'All', icon: '🍽️', description: 'All nutritious foods' },
  { id: 'drinks', name: 'Healthy Drinks', icon: '🥤', description: 'Zero sugar healthy beverages' },
  { id: 'shakes', name: 'Protein Shakes', icon: '🥛', description: 'No preservatives shakes' },
  { id: 'mealbox', name: 'Meal Boxes', icon: '📦', description: 'Complete nutrition meals' },
  { id: 'bowls', name: 'Power Bowls', icon: '🥗', description: 'Nutrient-dense bowls' },
];

export const nutrientFilters = [
  { id: 'vitamin-d', name: 'Vitamin D', icon: '☀️' },
  { id: 'omega-3', name: 'Omega-3', icon: '🐟' },
  { id: 'collagen', name: 'Collagen', icon: '✨' },
  { id: 'iron', name: 'Iron', icon: '💪' },
  { id: 'calcium', name: 'Calcium', icon: '🦴' },
  { id: 'protein', name: 'Protein', icon: '🥩' },
  { id: 'fiber', name: 'Fiber', icon: '🌾' },
  { id: 'antioxidants', name: 'Antioxidants', icon: '🫐' },
  { id: 'vitamin-b12', name: 'Vitamin B12', icon: '🔴' },
  { id: 'vitamin-c', name: 'Vitamin C', icon: '🍊' },
  { id: 'zinc', name: 'Zinc', icon: '⚡' },
];

export const techVendors = [
  { id: 'freshly', name: 'Freshly Farms', logo: '🌱', tagline: 'Farm to Table in 30 mins' },
  { id: 'nutribox', name: 'NutriBox', logo: '📦', tagline: 'Your Daily Nutrition Partner' },
  { id: 'greenbite', name: 'GreenBite', logo: '🥗', tagline: 'Healthy Eating Made Easy' },
  { id: 'vitadelivery', name: 'VitaDelivery', logo: '🚀', tagline: 'Superfoods at Your Door' },
  { id: 'purehealth', name: 'PureHealth Kitchen', logo: '💚', tagline: 'Zero Preservatives Guaranteed' },
];

export const nutritionFoods: NutritionFood[] = [
  // Healthy Drinks - Zero Added Sugar
  {
    id: '1',
    name: 'Green Detox Elixir',
    description: 'Fresh spinach, cucumber, celery, ginger & lemon - Zero sugar, 100% natural',
    price: 129,
    image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['iron', 'vitamin-c', 'antioxidants'],
    calories: 45,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '2',
    name: 'Beetroot Power Juice',
    description: 'Fresh beetroot, carrot, apple & ginger - Natural sweetness, no added sugar',
    price: 119,
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['iron', 'fiber', 'vitamin-c'],
    calories: 68,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '3',
    name: 'Coconut Water Fresh',
    description: 'Tender coconut water - Natural electrolytes, zero preservatives',
    price: 79,
    image: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?w=400',
    category: 'drinks',
    season: ['summer'],
    nutrients: ['calcium', 'zinc', 'antioxidants'],
    calories: 46,
    rating: 4.9,
    deliveryTime: '10-15 min',
    vendor: 'NutriBox',
  },
  {
    id: '4',
    name: 'Immunity Kadha Drink',
    description: 'Turmeric, tulsi, black pepper, ginger & honey - Ayurvedic immunity booster',
    price: 99,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400',
    category: 'drinks',
    season: ['winter', 'monsoon'],
    nutrients: ['antioxidants', 'vitamin-c', 'zinc'],
    calories: 35,
    rating: 4.7,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '5',
    name: 'ABC Morning Drink',
    description: 'Apple, Beetroot, Carrot juice - Zero sugar detox drink for clear skin',
    price: 139,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['vitamin-c', 'iron', 'fiber'],
    calories: 72,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'GreenBite',
  },
  {
    id: '6',
    name: 'Amla Aloe Vera Shot',
    description: 'Fresh amla & aloe vera - Vitamin C powerhouse, no preservatives',
    price: 89,
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400',
    category: 'drinks',
    season: ['all'],
    nutrients: ['vitamin-c', 'collagen', 'antioxidants'],
    calories: 28,
    rating: 4.6,
    deliveryTime: '10-15 min',
    vendor: 'VitaDelivery',
  },

  // Protein Shakes - No Preservatives
  {
    id: '7',
    name: 'Peanut Butter Banana Shake',
    description: 'Natural peanut butter, banana, oats & almond milk - 25g protein, zero sugar',
    price: 179,
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'omega-3'],
    calories: 320,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '8',
    name: 'Sattu Power Shake',
    description: 'Roasted gram flour, jaggery, cardamom & milk - Traditional protein drink',
    price: 129,
    image: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400',
    category: 'shakes',
    season: ['summer'],
    nutrients: ['protein', 'iron', 'fiber'],
    calories: 280,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '9',
    name: 'Ragi Almond Shake',
    description: 'Finger millet, almonds, dates & coconut milk - Calcium & protein rich',
    price: 159,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['calcium', 'protein', 'iron'],
    calories: 260,
    rating: 4.7,
    deliveryTime: '15-20 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '10',
    name: 'Spinach Avocado Shake',
    description: 'Fresh spinach, avocado, banana & hemp seeds - Green protein powerhouse',
    price: 199,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'iron'],
    calories: 290,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'GreenBite',
  },
  {
    id: '11',
    name: 'Dry Fruits Protein Shake',
    description: 'Almonds, cashews, walnuts, dates & milk - Natural protein bomb',
    price: 219,
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'vitamin-b12'],
    calories: 350,
    rating: 4.9,
    deliveryTime: '15-20 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '12',
    name: 'Moong Dal Shake',
    description: 'Sprouted moong, banana, jaggery & cardamom - Plant protein shake',
    price: 149,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    category: 'shakes',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 240,
    rating: 4.6,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },

  // Meal Boxes - Complete Nutrition
  {
    id: '13',
    name: 'Dal Roti Thali Box',
    description: 'Yellow dal tadka, 3 multigrain rotis, jeera rice & salad - Complete protein meal',
    price: 189,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 480,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '14',
    name: 'Baby Corn Stir-Fry Box',
    description: 'Baby corn, bell peppers, broccoli in garlic sauce with brown rice',
    price: 219,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['fiber', 'vitamin-c', 'protein'],
    calories: 380,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'GreenBite',
  },
  {
    id: '15',
    name: 'Paneer Tikka Meal Box',
    description: 'Grilled paneer tikka, mint chutney, whole wheat paratha & raita',
    price: 249,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'calcium', 'vitamin-b12'],
    calories: 520,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '16',
    name: 'Rajma Chawal Box',
    description: 'Punjabi rajma, jeera rice, onion salad & pickle - High protein comfort food',
    price: 179,
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 450,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'NutriBox',
  },
  {
    id: '17',
    name: 'Grilled Chicken Quinoa Box',
    description: 'Herb grilled chicken, quinoa, steamed veggies & hummus',
    price: 299,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'vitamin-b12'],
    calories: 420,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '18',
    name: 'Chole Bhature Light Box',
    description: 'Chana masala with baked bhatura (not fried), onion & green chutney',
    price: 169,
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 390,
    rating: 4.7,
    deliveryTime: '25-30 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '19',
    name: 'Palak Paneer Meal Box',
    description: 'Creamy palak paneer, 2 rotis, brown rice & cucumber raita',
    price: 229,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['iron', 'calcium', 'protein'],
    calories: 460,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'GreenBite',
  },
  {
    id: '20',
    name: 'Fish Curry Rice Box',
    description: 'Bengali style fish curry, steamed rice, dal & mixed veg',
    price: 279,
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400',
    category: 'mealbox',
    season: ['all'],
    nutrients: ['omega-3', 'protein', 'vitamin-b12'],
    calories: 480,
    rating: 4.9,
    deliveryTime: '30-35 min',
    vendor: 'Freshly Farms',
  },

  // Power Bowls - Nutrient Dense
  {
    id: '21',
    name: 'Mixed Sprouts Salad Bowl',
    description: 'Moong, chana, moth sprouts with lemon, tomato & green chutney',
    price: 149,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'vitamin-c'],
    calories: 180,
    rating: 4.8,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '22',
    name: 'Buddha Bowl Supreme',
    description: 'Quinoa, chickpeas, avocado, roasted veggies & tahini dressing',
    price: 269,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'omega-3'],
    calories: 380,
    rating: 4.9,
    deliveryTime: '20-25 min',
    vendor: 'GreenBite',
  },
  {
    id: '23',
    name: 'Egg White Veggie Bowl',
    description: 'Scrambled egg whites, sautéed spinach, mushrooms & whole wheat toast',
    price: 199,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'vitamin-b12', 'iron'],
    calories: 280,
    rating: 4.7,
    deliveryTime: '20-25 min',
    vendor: 'VitaDelivery',
  },
  {
    id: '24',
    name: 'Poke Bowl Fresh',
    description: 'Brown rice, edamame, cucumber, carrot, tofu & sesame ginger dressing',
    price: 289,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'omega-3', 'fiber'],
    calories: 340,
    rating: 4.8,
    deliveryTime: '20-25 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '25',
    name: 'Mediterranean Bowl',
    description: 'Falafel, hummus, tabbouleh, olives & whole wheat pita',
    price: 239,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'fiber', 'iron'],
    calories: 420,
    rating: 4.8,
    deliveryTime: '25-30 min',
    vendor: 'Freshly Farms',
  },
  {
    id: '26',
    name: 'Oats Upma Bowl',
    description: 'Steel cut oats upma with vegetables, peanuts & coconut chutney',
    price: 139,
    image: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['fiber', 'protein', 'vitamin-b12'],
    calories: 260,
    rating: 4.6,
    deliveryTime: '15-20 min',
    vendor: 'NutriBox',
  },
  {
    id: '27',
    name: 'Millet Khichdi Bowl',
    description: 'Foxtail millet, moong dal, ghee & mixed vegetables - Gut-friendly',
    price: 159,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['fiber', 'protein', 'iron'],
    calories: 290,
    rating: 4.7,
    deliveryTime: '20-25 min',
    vendor: 'PureHealth Kitchen',
  },
  {
    id: '28',
    name: 'Chicken Tikka Bowl',
    description: 'Grilled chicken tikka, mint rice, grilled veggies & yogurt dip',
    price: 279,
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400',
    category: 'bowls',
    season: ['all'],
    nutrients: ['protein', 'vitamin-b12', 'zinc'],
    calories: 380,
    rating: 4.9,
    deliveryTime: '25-30 min',
    vendor: 'VitaDelivery',
  },
];
